name: rick_and_morty
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage:
  http: ^1.3.0
  connectivity_plus: ^6.0.0
  sqflite: ^2.0.0+4
  path: ^1.8.0
  confetti: ^0.8.0
  curved_navigation_bar: ^1.0.6
  change_app_package_name: ^1.5.0
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.4.1
  lottie: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.4"
  flutter_native_splash: ^2.4.5

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"


flutter_native_splash:
  color: "#ffffff"
  image: assets/images/icon.png
  android: true
  ios: true



flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/